Решение проекта "Валидация банковской карты"
Elena-web/javascript pull request #12
Opened 2024-04-03 13:49 UTC by Elena-web

2024-04-03 16:08 UTC, burtovoy requested changes

2024-04-03 16:08 UTC, burtovoy commented on luhn/luhn.js
> +  if (arr.length > 1 && /^[0-9\s]+$/.test(str) && arr.length <= 20) {
Давай без регулярных выражений сделаем решение

2024-04-03 16:08 UTC, burtovoy commented on luhn/luhn.js
> +      if ((arr.length % 2 === 0 && (i === 0 || i % 2 === 0))
Слишком сложная логика - нужно упростить

2024-04-04 06:37 UTC, Elena-web commented on luhn/luhn.js
> +  if (arr.length > 1 && /^[0-9\s]+$/.test(str) && arr.length <= 20) {
Сделала через метод для массива, посмотри

2024-04-05 22:13 UTC, merged