Task 6
Elena-web/javascript pull request #6
Opened 2024-03-11 16:28 UTC by Elena-web

2024-03-12 17:46 UTC, burtovoy requested changes
Мы линтер настраивали? Что-то код поехал

2024-03-13 07:44 UTC, Elena-web commented
> Мы линтер настраивали? Что-то код поехал

Я внесла изменения

2024-03-13 21:29 UTC, burtovoy commented
конфликты

2024-03-13 21:29 UTC, burtovoy requested changes
конфликты

2024-04-26 16:20 UTC, closed without merging